#spring.application.name=basic
spring:
  application:
    name: est-service-dev

  devtools:
    restart:
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8

kakao:
  api:
    key: 1234567890

server:
  port: 8081